#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^((sprint|epic|user_story)[0-9])\/(feat|fix|doc|hotfix|refactor|refac|test)_(task|[a-zA-Z]+)_[0-9]+$"

message="\n\n\n"
message+="Nome da branch esta invalida.\n"
message+="O nome da branch deve estar no formato:\n\n\n"
message+="sprint0/feat_task_0\n\n"
message+="sprint0/fix_task_0\n\n"
message+="sprint0/doc_task_0\n\n"
message+="sprint0/hotfix_task_0\n\n"
message+="sprint0/refactor_task_0\n\n"
message+="sprint0/refac_task_0\n\n"
message+="sprint0/test_task_0\n\n\n"
message+="Altere o nome da branch."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo -e "$message"
    exit 1
fi

exit 0